// target.client/app/components/InputField.tsx
import React from 'react'

interface InputFieldProps{
  label:string;
  type:string;
  placeholder?:string;
  htmlFor:string
}
export const InputField = ({label, htmlFor, type, placeholder}: InputFieldProps) => {
  return (
    <div className='pb-4'>
     <label className='block font-semibold text-sm ' htmlFor={htmlFor}>{label}</label> 
     <input className='rounded-md w-full text-sm p-2' type={type} placeholder={placeholder} id={htmlFor}/>
    </div>
  )
}

// target.vue/components/InputField.vue
<template lang="">
  <div class="mb-4">
    <label :for="htmlFor" class="block font-semibold text-sm ">{{label}}</label>
    <input class="rounded-md w-full text-sm p-2 border border-gray-300 outline-none transition-all focus-within:border-zinc-600 focus-within:transition-all"  type="text" :placeholder="placeholder" :id="htmlFor"/>
  </div>
</template>
<script setup>
  defineProps({
    label: String,
    type:String,
    placeholder:String,
    htmlFor: String
  })
</script>
<style lang="">
  
</style>
