// target.vue/components/Accordion.vue
<template lang="">
  <div>
      <h3 @click="isActive = !isActive" class="p-4 text-sm font-semibold cursor-pointer border-b">
        {{header}}</h3>
        <div :class="['p-5' , isActive ? 'block' : 'hidden']">
          <slot></slot>
        </div>
    </div>
</template>
<script setup>
  let isActive= ref(false)
  function toggleIsActive(){
    return isActive = !isActive
  }
  defineProps({
    header: String  
  })
</script>
<style lang="">
  
</style>

// target.client/app/components/Accordion.tsx
import { useEffect, useState } from "react"

interface IAccordionProrps{
  header: string
  children: React.ReactNode[]
  className?: string
}
export const Accordion = ({className, header, children}: IAccordionProrps) => {
  const [isActive, setIsActive] = useState(false)
  useEffect(() => {toggleAccordion}, [isActive])
  const toggleAccordion = () => isActive == true ? 'block' : "hidden"
  

  return (
    <div>
      <h3  onClick={() => setIsActive(!isActive)} className={`p-5 text-sm font-semibold cursor-pointer border-b ${className}`}>
        {header}</h3>
      <div className={`p-5 ${toggleAccordion()}`}>
        { children }
      </div>
    </div>
  )

  
}
